name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    # Говорим серверу: "Все команды выполняй внутри папки frontend!"
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Скачиваем код
        uses: actions/checkout@v4

      - name: Устанавливаем Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Скачиваем зависимости
        run: flutter pub get

      - name: Собираем iOS (без подписи)
        run: flutter build ios --release --no-codesign -v

      - name: Упаковываем в IPA для Sideloadly
        run: |
          mkdir -p build/ios/iphoneos/Payload
          mv build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/
          cd build/ios/iphoneos
          zip -r gigafit.ipa Payload

      - name: Выдаем готовый файл
        uses: actions/upload-artifact@v4
        with:
          name: gigafit-ipa-file
          # Здесь тоже указываем, что артефакт нужно забирать из папки frontend
          path: frontend/build/ios/iphoneos/gigafit.ipa